name: Mini project on CI

on:
    pull_request:
        branches:
          - main
    workflow_dispatch:
jobs:
    validate:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Provide permissions to script
              run: chmod +x ./scripts/*.sh

            - name: Run CI Summary
              run: ./scripts/ci_summary.sh